---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: slskd-tls
spec:
  secretName: slskd-tls
  dnsNames:
    - "${SECRET:DOMAIN_SLSKD}"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
