---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  volumeName: pvc-cdae88e3-5138-47d6-b8ee-1c86a5e26111
  resources:
    requests:
      storage: 2Gi   # slskd.db (peer/search/transfer state)
