---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: semaphore-age
  namespace: semaphore
spec:
  encryptedData:
    keys.txt: AgBh74sSPJFyoRy2CQIJlzozjVD21PdOrWqvfLsLOhp0gUyf/Bb6yRtag6yNKcyiYvcNOHW/hWvcwF8YOZdC0bmP+lhEOrVGc7BrHbOAsQM8jPGW4PgUk8BeKP4zIcQm/VjHKgBLeDXHXf+RMlF+I7UsNdja7sknC3N1GlZfJCQIYUvi70+7QuCPFLWLQXIZbXLGknaRHLqvO2lgQ8BABWUaSVRqNt0DOTvPad39LTUOjygYXfhP3BehFsP0SNS+fIH4N2SbHWqtcTTxqJgWWOEZIb9Oa6K0SeT7oeCknz3/t1J3SEcDQAJpZuWy0m5dhTQL4H7nWtuq+jR3U740liOlDK5oJXaw5wZ1DLp1SIEcxhDcAklt5XL0CXwd9VLIlc+2/8RCM87unPSeOf7WJzA+mjaSWcXO4IfgNi6DpXCtEr0FfSzvVfMOBtz/dBnrsmG5+EBfHX1P5/xIX5a5dn8+1lSiEscDHbSUBe8/9v0eg2dXsIdLED+BITg0dlQTjODhAWSCCzKmUwgjKCnhDUkN9LYX9BUpWYmit/BLgqbWNQhBKqvxCSJX8JQYrcRPezfQqnwHrR5Lsv1BM+aCnOrtBmG+Z1PCLUfwVNXHtziqpDPOXj9vH7jSPNKLCiaweWOrsQwcaTSCB4vFsBIiPhH3uqVULCdNBU3nM3UAQNPdndDfqTwjoUk2tfGcV1rbzI/exR3umBJE2BzxWSDBFQSJB7l9OrDYGGUCgh3/tSCUQTqwKj56WWf9yESOYLHhaPBe+47rg35eg7/zR5IFuvmfP2r7dV4djiMAN6AV6AdNeKjGe0DqOtAW8lgfr3L8E6U8m6JmL3x9OYCvIdpQLe3ZkVMJL3qepb0TtgTLYRUYsguJG11q8L0YhLurLtWwaYJdIrLtJbU/DEjaTK8OnBdTD+9jbuxbxFN3s4l1qbeGPwx8PLJGulktcJv4n5M=
  template:
    metadata:
      name: semaphore-age
      namespace: semaphore
