---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-secrets
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_PROXMOX_TOKEN_ID: AgBXKpIp4grDA9MVFwVfalKZuhsL+30dkNf6DvdWRoyOM9iWqb5P9fN+GUjrn6MgZLirGFb6iCkFy9sWD4SFv5TJt/vk+l1A6u9RnRzUCSLI0HOeaRnkrNMSSXFAOnTDGgRxrCsHPxjOEEEN5d8DZorC25rO17a8FNKF1K9g8VsoL6uUJSrSVe9s15b7t5cGawawlGedldFFwcG505ZfpJM1lSqJDqePo8d0V/X3xrJZLhBXO8fv7IbwKatWaCpltHQiBc0RcvZxl5opZ02m0u0L3MedmrsnejUr5QpSGii5S4vGfvcWJoUSd9lo57Cs6+qqBUSt54LpMYg/DrSiazeiFrNtF/CRIz7XKq+TJ+iXdMwnsjDjadbw7OiHpQNrhtnBWPJoEwBiLeTXi2Fzxs+eBKIPewY6WNUoTJzCQrsWtNPaeBxcE9kQv+HK+N4BnatEjmcOWxkB43XUwmtshShfyITO1WDdk5KYyx/t8B+psAuNO7sW84nMf4ICgIodrLmnRpd/7YtGHlwXfmMrkvr3A6zbcTaphz/WNPW2iPnyZW3xVZ7I8E0Jihg3U8WOwvkIAP8O+2T+XHrtw9GzRF/sEsUTAvtdj9ueCmMxNihqGHNyxHkVkmfy68ZgQ/53/HPdyKL+w7TBva3QzsVmqm178T5Mv0NkKA7L4t8R1HUHTx9i1pEF3K2dtAlTl8/IXaVy79FUcke9pszsjUcBhTvRssBybJjZ
    HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET: AgB0L7UVnvGT9linuSjlcVtQI7h+KCzv8UTxWfAaglrpfRJDhjIgO5mkE3Mc9Ah22hUycLcaeFyFYhxtji9kRm6cNP8RrQ+CkHCRI673lEOM3GjlNNlc5mtQ4YzitcTy72l95+Br24wTS+/OCvK9VsDhA6+3TDFvw8VqKwqT2LWYKosGy6Fw0YLC7w3YIrHUexQ/jZy+oSPcQRQ216oipPM/ALjPfwl0k5yrWjDYdGuhDJoqx4kJryuxITiDHv68JjdrxSeYJNO4EP0nPIJKrQj5hx4KgkW19+/BaBZ9cmItZlQxf6jcYKGRI5Dr85y+mZRYKsXRene3Difyo4m4AbLwj8q974ZdPFZQWMWsmaRgu4WLo6qDevuvSb64QRs+c9L5dDEx4X2efgS3V78Itk7Ldk01uap6XsbNFUcTedu5o/Yn6EdCv2zfwt+fswhzGGngHaxGLDafHgx/T2kd2kaA50FK556SXhJLSPOk0QKkJVaTdD1nqv4KGWpghsywk1vQ1OMuB0//Wh8VpCbsjuTCiVDWFCKk2JQWXXvQbGwRX3zVbTLQmgyiFmryQBuhTOwxwbWNyk/syN405GzclEAWqdqpqsjSi4QmcJyB2iDbCj1b+sDcXHkYZ341ZzenBb+bri7HQpSE4OlKyknChKyKRjna6YrnTL+k2seGZzI16RFE0EDpiM696+M94hGBi6RShIH1YttVMeu4olyYyrBSVqBkytVZpvfZD5kYZu54pIB60jg=
  template:
    metadata:
      name: homepage-secrets
      namespace: homepage
