---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ops-alerts-secrets
  namespace: ops-alerts
spec:
  encryptedData:
    NTFY_TOKEN: AgCFal+0sKNJbXKGW6aGm/KiCMV1gNZZT8+D7CBwBRO0t26CBRnWpSZ5BC10vbB+tN2rkOlDTSM52UfDFRZSvduSO7QLNtKcVxFs5DOo4BnPTZzdd5IlIaxkdlrQrwGRTS/1Pu8bMuIV/+qNOKo2rW0/SuazBU/b+9LlDn3N346E3ZEzPkevdxKumx1SCsgrF5SwqAnp17LtIrZDJPSxuWV7AzCJPyPJVAnPjA0g+cmPLOQMk1ha3rxuss1CEElNs7m5mptdl2GKEeKHQh6Ow4TepxEOF1SKAuQFZeQt0ksTMHnSREmamE2aXcoPkROkDxQquFuc/tJ30WUsmxTjp/3YpbiBZxMTHMutUlaa05FW7xCPqbeb47ocib3aiA4M2CE3a5HojSAjCY4ChyNE8ve5ruEVRItKPYBz7oirYufq7aZo3flVFS0VjNeN+rcPkSw9ygvFDyKXxm2PAxTx0iUoOm+uyqZQtp4mI3yoJwkWx760Uq4w4BRnriwH9GkQslL2toWXlAF07/aBfY5IQCakXaJ1VyCIJdfIAdVq3Yzn7D+uJVReU+fHUwkAJcsD/TeprGqK4iKsa5ez4jAagMBPt4xa1ZXP943KCcOzzqgnH9QQY220/f5m9cShKkRBmC8p1x8volfX+5+D2fT6rIQgPbWyIEumeONpJAkQw4ne2m6BhX8edpifdXGsGorAieHMbxwT6YYZ73mlt01iTiiGB84a4V3Bdjjaoe4CroBDPA==
  template:
    metadata:
      name: ops-alerts-secrets
      namespace: ops-alerts
