---
- Apps:
    - Suwayomi:
        - icon: suwayomi.png
          href: https://${SECRET:DOMAIN_SUWAYOMI}
          description: Comics admin
    - Semaphore:
        - icon: semaphore.png
          href: https://${SECRET:DOMAIN_SEMAPHORE}
          description: Ansible Semaphore
    - NanoKVM:
        - icon: mdi-monitor-dashboard
          href: https://${SECRET:DOMAIN_KVM}
          description: KVM console
- Links:
    - GitOps repo:
        - icon: github.png
          href: https://github.com/sushistack/homelab-gitops
    - Cloudflare:
        - icon: cloudflare.png
          href: https://cloudflare.com
- Reference:
    - Homepage docs:
        - abbr: HP
          href: https://gethomepage.dev
