---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgATKRf8yO3SCw6a9fCBeWomfN0iMKPtt2sh7smwEN/zah8Za80IUHCNY0VZnxcmKi2Xq0uXB6gJR3iKj/8JK3fo9DHkcCp0CCrYKpqrudYRycmZ3xWBkw7Bm+1pngb/qCpdYlA/UtHzz3Cny1j9yHy6zYI5vabdEmf74wa6lXUnGqf9acXP5zCe2PZCjUd9DL8dPCgFR0UtTsQZ2ZJmnUqFjtEB8UqqeSk1onpyE40RN3uTquF3zc5VGRt4svoeEg14ck+AI15ehpiXVXBpopbU5RVa34Yx6zvIeeUmkWqbuIqfGozjVpHEWA8d+Rnhxzo7MHa6wGc58iCFWNok2c7NuBhk//iN5o24eO3/Gl4s7YyJN9cDOwQ7ptguEEBRoDJPPGItZrD3SzR/EWpgET8TIs2vPNuUJi1ZGeNSXmlmAzPnLHzNV1u54I7tgTbB4tye4wBeDslvOrfLWVHn35M5+QQb9kC19Ur5xisNp25+YNDyZI0yZL6/9UCjJiss0P6nJnSm72XmhluIq+0b0/bQRs7DTtqjRGl8drUFNcI1KXa1RO4lGmrAitu+zjdZcKUplFwDq0oApFHAqBLVybD2Vv/r9tXRZ/hT0AnUEpvttX4kuIXxR+IK6xM9JHaLJ8dYYEdgsaJbHk3nhcw90gA/jXwBxC8QgxobdKZrsC6Kxb6pDMSBHUz98xGOy8d0M1MDM1YWsrH5fE6C44DIsrUZvMDp/85+rXLw3KeQICP/3eGh+SbCaJTvO5P8UMqeJlVz7T6yR4cR+6joUTdHWZWepJnWnsCJQCAePs4Nu7tP8z2ZaobbonnlNSOd0vhgG3HPDC76RDNGWSmTPz5CHE4xsKxR+HsS7alNlJ5pOmyewCo37qTCLfGLzfv1B9cdj6H2GC7rF/orQGkdSDgzRZXP6LWCCt9r
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
