---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    TUNNEL_TOKEN: AgCC7FZMWu/3sCkjXPXZ6s1xQ23qe7+Ix5h4w03dc5gwaiOGXG630txp/1YmPd5nPQ7Oe43bJUA3ZTVJzQkpJv/590+Ei2gcirY8gUTdda4YMuTL+ZFznALHN3sWfMkkIZfqDr5JcQhALVfH7zBz5FxyeAxyXBs+9zyCttjL6v9ugQUhJWz2I0gunAsyIx7taVXGio0ZbsIIm7i7NY/OMfy9Vnjps12U6pH/SRIFjLBSLhGUQtjlPvdM9wJQ4FrZLIFYXzTH9dyaBSRQAZPIB9zJ/W/pq7O41COWPRXqhmwfwGgnQ+JHgYC3PXkgyrWBBuLtQ5AfHjqPJu3rrE9PZxvfkuGCo/q1Nd2KI78/MXL6+f6bi7SjO0D2wMiF6VMV4IGOuVsb/mM6Khigr+UVJ+C5rF5CfIWCupPMLgf0VcA1biu/+8yOQbYhx2jQdMEwdcy5yV6y5RVn5ySOVWz6iAjNIhBUP50IXDoVctwPLf1u4XHJjy4De9CuSd1edfIiFG8IVGPQpxdP4YbASKjQ56z6dWvije4xamXOYGoFUTCp0AS4164RheYJuvep9ty1rLrZoOv6uNnbmuee4pM7swxDUoyMrbSfSYJrrxCTneN0bSd3XSqKmsWwBfnHPsdN5FDVJN1aj2NwkqJvn7+w59Sf612oVfxOghEh9Tp7YcxCOAmrmkCcuuv0RKeRKYrWInUwIA8xWpTBQHS2AWCVsu2vJvY7HHgW30FIQCHsHxPLOUE6a5uqXQNmJkTKrwAXA+ZSeIXlo/8YOdPrj57ldl2i+CwG5qZAsIK4Cuxn/t6idjgC5zNoxNMYSSPAbPfGa4iGki19gEWbUjyd2rfPTSp3bM6oehSolhyKzJoKZBLa+1GceBmjophKi1O05vJ9EOUsyit0npBE8wHz7wM7Q5LeD1n5u8nUEF8aHZ8QDptjC9FhxhsZ7kwa
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared
