---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgA0CUFHvsXHiH6k7LDBEYJN7VCfptYb42Qtuk9ExXK8i816/CCVJYGd1M5WEVzKE4vdozHwkKgutt44XLwHdKcZuUOeNBJbZuJbaNTgCTX6yT00yLKuDR8MOSJMYmfWI5xtKoar3VZnV19uSalYoAxkuhtg/QbcY2qbAMRbQHn7fCl6qak5p2K++WFNoTm08CkuiNPXOgIj6XJY6v1jFhZ1Va3FBYClTVADmTgorZ9yls3R8y0atQG7GIh8lBWOV1u9wDMNKVeugV8pqntFQ12puDBuBVJWZv1BrMNR7anD4lKarW/3ANiewYxE4x+zogoehovtr9INsMpdxqqQ1E7e1acxUyRBXhBTQY1vV2m6Z0nQh6EGMaHdHN4bky49fAGXrm0US8FPwIxJmW7YTC4kL9bmMZAx+lFUfL9tWOfYRp0pltdvO4qtoiw1OS0DqH1cp/8QB0rOqhhOCefDOAjygoWyzM9J8uNBD/rX0BnnkcU5g4zv4WPxBBjrwS+/89eGASG7UkGd9jI+McpQiPBkZRfxUq6cvskZwl3UpQaWpx+t5MAQTWNkI6lOqVE5MiZfmB2H5Ol2RvuWLL1lMns0q7J47Xz1py7hcUGO+k5DNUic/wko4qe/14D8Ph/Lw2A59r2v5xiFsfu94Qpur9xlAG1cCBP5oHsP0FoXTnDkIDY6Rv8UZ0eaXtWMozoR2kPbnp0c06CSdx6nM16j31wsCDqywdyOZzw2Ic01ZzikZ2T5rl3qC2jfa35jKpAlyauroEDM7GHL4U7YQ4E81k51ukLpP7WzIb0QGJZwRGSfezu8WPHXJLrPyAG396RsjPjcYB5t1sBDRo8DS5hPzrExUtSUrsqgiHhKfpXLX7Vx0Hpq+PHMUmMAoRkGdHl55h0Qtixj+drwe0HtDpAvOyd20WN/5Mbs5JXGxI8=
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
